delimiter %%
CREATE PROCEDURE InsertRecords()
BEGIN
	INSERT INTO FinalProject.Autores (nombre, nacionalidad, fecha_nacimiento, biografia, fecha_defuncion, lugar_nacimiento) VALUES
	('Gabriel García Márquez', 'Colombiano', '1927-03-06', 'Escritor y periodista colombiano, conocido por su obra maestra "Cien años de soledad". Ganó el Premio Nobel de Literatura en 1982.', '2014-04-17', 'Aracataca, Colombia'),
	('J.K. Rowling', 'Británica', '1965-07-31', 'Autora británica, famosa por la serie de novelas de Harry Potter. Sus libros han sido un fenómeno literario mundial.', NULL, 'Yate, Inglaterra'),
	('Paulo Coelho', 'Brasileño', '1947-08-24', 'Escritor brasileño, conocido por sus obras de ficción y autoayuda, como "El Alquimista" y "Veronika decide morir".', NULL, 'Río de Janeiro, Brasil'),
	('Jane Austen', 'Británica', '1775-12-16', 'Novelista británica, considerada una de las escritoras más importantes de la literatura inglesa. Sus obras incluyen "Orgullo y prejuicio" y "Sensatez y sentimientos".', '1817-07-18', 'Steventon, Inglaterra'),
	('Mario Vargas Llosa', 'Peruano', '1936-03-28', 'Escritor peruano, ganador del Premio Nobel de Literatura en 2010. Sus obras más destacadas son "La ciudad y los perros" y "La fiesta del Chivo".', NULL, 'Arequipa, Perú'),
	('Haruki Murakami', 'Japonés', '1949-01-12', 'Escritor japonés contemporáneo, conocido por sus obras de ficción surrealista y sus temas sobre la alienación y la soledad. Algunos de sus libros famosos son "Kafka en la orilla" y "La balada del café triste".', NULL, 'Kioto, Japón'),
	('Isabel Allende', 'Chilena', '1942-08-02', 'Escritora chilena, reconocida por sus novelas de realismo mágico, como "La casa de los espíritus" y "Eva Luna".', NULL, 'Lima, Perú'),
	('Stephen King', 'Estadounidense', '1947-09-21', 'Autor estadounidense de novelas de terror y suspense. Sus obras más conocidas son "It", "El resplandor" y "El señor de las moscas".', NULL, 'Portland, Maine, Estados Unidos'),
	('Chimamanda Ngozi Adichie', 'Nigeriana', '1977-09-15', 'Escritora nigeriana, autora de novelas como "Americanah" y "Hibisco Púrpura". Su trabajo explora temas de raza, identidad y feminismo.', NULL, 'Enugu, Nigeria'),
	('Fyodor Dostoevsky', 'Ruso', '1821-11-11', 'Novelista ruso, considerado uno de los escritores más influyentes de la literatura universal. Sus obras más famosas son "Crimen y castigo" y "Los hermanos Karamazov".', '1881-02-09', 'Moscú, Rusia'),
	('Toni Morrison', 'Estadounidense', '1931-02-18', 'Novelista, editora y profesora estadounidense. Ganó el Premio Nobel de Literatura en 1993. Sus novelas, como "Beloved" y "La isla de los caballeros", exploran temas de raza y identidad afroamericana.', '2019-08-05', 'Lorain, Ohio, Estados Unidos'),
	('Gabriel García Márquez', 'Colombiano', '1927-03-06', 'Escritor y periodista colombiano, conocido por su obra maestra "Cien años de soledad". Ganó el Premio Nobel de Literatura en 1982.', '2014-04-17', 'Aracataca, Colombia'),
	('J.K. Rowling', 'Británica', '1965-07-31', 'Autora británica, famosa por la serie de novelas de Harry Potter. Sus libros han sido un fenómeno literario mundial.', NULL, 'Yate, Inglaterra'),
	('Paulo Coelho', 'Brasileño', '1947-08-24', 'Escritor brasileño, conocido por sus obras de ficción y autoayuda, como "El Alquimista" y "Veronika decide morir".', NULL, 'Río de Janeiro, Brasil'),
	('Jane Austen', 'Británica', '1775-12-16', 'Novelista británica, considerada una de las escritoras más importantes de la literatura inglesa. Sus obras incluyen "Orgullo y prejuicio" y "Sensatez y sentimientos".', '1817-07-18', 'Steventon, Inglaterra'),
	('Mario Vargas Llosa', 'Peruano', '1936-03-28', 'Escritor peruano, ganador del Premio Nobel de Literatura en 2010. Sus obras más destacadas son "La ciudad y los perros" y "La fiesta del Chivo".', NULL, 'Arequipa, Perú'),
	('Haruki Murakami', 'Japonés', '1949-01-12', 'Escritor japonés contemporáneo, conocido por sus obras de ficción surrealista y sus temas sobre la alienación y la soledad. Algunos de sus libros famosos son "Kafka en la orilla" y "La balada del café triste".', NULL, 'Kioto, Japón'),
	('Isabel Allende', 'Chilena', '1942-08-02', 'Escritora chilena, reconocida por sus novelas de realismo mágico, como "La casa de los espíritus" y "Eva Luna".', NULL, 'Lima, Perú'),
	('Stephen King', 'Estadounidense', '1947-09-21', 'Autor estadounidense de novelas de terror y suspense. Sus obras más conocidas son "It", "El resplandor" y "El señor de las moscas".', NULL, 'Portland, Maine, Estados Unidos'),
	('Chimamanda Ngozi Adichie', 'Nigeriana', '1977-09-15', 'Escritora nigeriana, autora de novelas como "Americanah" y "Hibisco Púrpura". Su trabajo explora temas de raza, identidad y feminismo.', NULL, 'Enugu, Nigeria');

	INSERT INTO FinalProject.Libros (titulo, autor_id, año_publicacion, genero, idioma, numero_paginas, precio) VALUES
	('Cien años de soledad', 1, 1967, 'Realismo mágico', 'Español', 471, 25),
	('Harry Potter y la piedra filosofal', 2, 1997, 'Fantasía', 'Inglés', 223, 15),
	('El Alquimista', 3, 1988, 'Ficción', 'Portugués', 208, 18),
	('Orgullo y prejuicio', 4, 1813, 'Novela', 'Inglés', 279, 12),
	('La ciudad y los perros', 5, 1963, 'Novela', 'Español', 416, 22),
	('Kafka en la orilla', 6, 2002, 'Ficción', 'Japonés', 505, 20),
	('La casa de los espíritus', 7, 1982, 'Realismo mágico', 'Español', 496, 24),
	('It', 8, 1986, 'Terror', 'Inglés', 1116, 28),
	('Americanah', 9, 2013, 'Ficción', 'Inglés', 588, 26),
	('Crimen y castigo', 10, 1866, 'Novela', 'Ruso', 671, 16),
	('Beloved', 11, 1987, 'Ficción', 'Inglés', 324, 20),
	('El amor en los tiempos del cólera', 1, 1985, 'Realismo mágico', 'Español', 368, 22),
	('Harry Potter y la cámara secreta', 2, 1998, 'Fantasía', 'Inglés', 341, 17),
	('Veronika decide morir', 3, 1998, 'Ficción', 'Portugués', 208, 15),
	('Sensatez y sentimientos', 4, 1811, 'Novela', 'Inglés', 351, 14),
	('La fiesta del Chivo', 5, 2000, 'Novela', 'Español', 576, 25),
	('La balada del café triste', 6, 1989, 'Ficción', 'Japonés', 304, 18),
	('Eva Luna', 7, 1987, 'Realismo mágico', 'Español', 384, 21),
	('El resplandor', 8, 1977, 'Terror', 'Inglés', 659, 24),
	('Hibisco Púrpura', 9, 2003, 'Ficción', 'Inglés', 307, 19),
	('Los hermanos Karamazov', 10, 1880, 'Novela', 'Ruso', 824, 23),
	('Sula', 11, 1973, 'Ficción', 'Inglés', 192, 17),
	('Del amor y otros demonios', 1, 1994, 'Realismo mágico', 'Español', 368, 20),
	('Harry Potter y el prisionero de Azkaban', 2, 1999, 'Fantasía', 'Inglés', 435, 18),
	('El peregrino', 3, 1987, 'Autoayuda', 'Portugués', 240, 16),
	('Persuasión', 4, 1817, 'Novela', 'Inglés', 272, 13),
	('Travesuras de la niña mala', 5, 2006, 'Novela', 'Español', 326, 21),
	('Tokio Blues', 6, 1987, 'Ficción', 'Japonés', 384, 19),
	('Inés del alma mía', 7, 2006, 'Realismo mágico', 'Español', 336, 23),
	('El ciclo del hombre lobo', 8, 1983, 'Terror', 'Inglés', 432, 22),
	('Algo anda mal', 9, 2014, 'Ficción', 'Inglés', 276, 18),
	('Noches blancas', 10, 1848, 'Novela', 'Ruso', 144, 12),
	('El ojo más azul', 11, 1970, 'Ficción', 'Inglés', 216, 15),
	('Memoria de mis putas tristes', 1, 2004, 'Realismo mágico', 'Español', 128, 17),
	('Harry Potter y el cáliz de fuego', 2, 2000, 'Fantasía', 'Inglés', 636, 20),
	('Aleph', 3, 2011, 'Ficción', 'Portugués', 272, 19),
	('Emma', 4, 1815, 'Novela', 'Inglés', 464, 16),
	('El sueño del celta', 5, 2010, 'Novela', 'Español', 480, 24),
	('After Dark', 6, 2004, 'Ficción', 'Japonés', 208, 17),
	('El plan infinito', 7, 1991, 'Realismo mágico', 'Español', 320, 22),
	('Misery', 8, 1987, 'Terror', 'Inglés', 368, 21),
	('Aquí hay belleza', 9, 2022, 'Ficción', 'Inglés', 272, 23),
	('El idiota', 10, 1868, 'Novela', 'Ruso', 672, 18);
END
%%

CALL InsertRecords();